### ISSUE TITLE
REFACTOR: API

### ISSUE THREAD

**Issue by ferferga** [ispp-2324-ocial/backend#110]
Algunas mejoras para evitar solicitudes múltiples y mejorar la velocidad de la aplicación.

* **POST** /api/event/create: En su respuesta debería de devolver el nuevo evento creado
* **GET** /api/event/{id}/like: Los likes del evento deberían de venir en la propia entidad ``Event``, sin tener que hacer una solicitud extra.
* Deberíamos de plantearnos si vamos a mostrar o no quien le ha dado like a un evento (yo pienso que **NO** deberíamos de complicarnos). Si no vamos a mostrar quien le ha dado like a un evento, lo único que tendríamos que devolver es una propiedad ``likes`` dentro de Event y evitar exponer la entidad de forma innecesaria.
* Para crear un evento es necesario pasar el ``ocialClient``, esto es innecesario cuando ya está la información del usuario actual en la solicitud.
* La entidad djangoUser y OcialClient debería de unirse en una sola (``User`` a secas) a nivel de vistas, es problema de seguridad exponerle a todo el mundo que el framework con el que funciona la aplicación es Django e igual complica la lógica de las vistas (en frontend) y hace que haya que hacer múltiples solicitudes al backend.

**Comment by adrrf** [comment]
Lo de la entidad djangoUser y Ocial client no se pueden unir, hay que separar responsabilidades.
Lo de los likes, significaria que hay que tener un elemento que puede estar ctemente cambiandose, muchar operaciones, ademas si interesa quien ha dado like ya que un usuario podrá ver los eventos a los que le ha dado "like"

**Comment by ferferga** [comment]
Una cosa es el modelo interno de datos que tengáis y otra cosa los serializadores. @carvarsou Te puede contar más de eso de la primera refactorizacion que hizo.

No hay ninguna necesidad de tener dos entidades diferentes y en muchos sitios tenemos que hacer 2 solicitudes para los datos del usuario, y los usuarios pilotos nos han dicho que es necesario mejorar esto, por lo que es prioridad alta.

En el caso que me dices, entonces como cliente solo nos interesa una lista de los eventos bajo GET /api/events/liked

**Comment by ferferga** [comment]
A la velocidad de la aplicación, teniendo distinción entre ambos significa que en algunas vistas hay que hacer dos peticiones (una para ocialClient y otra para djangoUser)

**Comment by adrrf** [comment]
> A la velocidad de la aplicación, teniendo distinción entre ambos significa que en algunas vistas hay que hacer dos peticiones (una para ocialClient y otra para djangoUser)

peticiones para? una posible solucion seria devolver el usuario de django junto al cliente

**Comment by adrrf** [comment]
a lo de los likes, en el get by id pondre que el serializer devuelva la cantidad de los likes

**Comment by carvarsou** [comment]
@adrrf Creo que cuando Fernando habla de unir DjangoUser y OcialClient es de cara a frontend. Nosotros en backend vamos a seguir teniendo dos entidades separadas, entonces en todos los serializadores se va a unir los atributos de ambas entidades para llamar desde frontend una sola vez.

**Comment by adrrf** [comment]
sisi, ya lo he entendito

**Comment by ferferga** [comment]
@ispp-2324-ocial/backend El punto 4 no se ha resuelto

**Comment by ferferga** [comment]
@ispp-2324-ocial/backend @carvarsou Es innecesario tener que pasar una entidad like a la hora de crearla.

**Comment by ferferga** [comment]
El parámetro ``all`` en ``GET /api/event/list/`` es innecesario, es decir, si ningún otro parámetro es pasado al request, deben de devolverse todos, si algún otro parámetro está dado, los del filtro. Es redundante, además de que entra en conflicto con los demás.

**Comment by carvarsou** [comment]
> El parámetro `all` en `GET /api/event/list/` es innecesario, es decir, si ningún otro parámetro es pasado al request, deben de devolverse todos, si algún otro parámetro está dado, los del filtro. Es redundante, además de que entra en conflicto con los demás.



> @ispp-2324-ocial/backend @carvarsou Es innecesario tener que pasar una entidad like a la hora de crearla.



> @ispp-2324-ocial/backend El punto 4 no se ha resuelto

Resueltos todos en #116.
