### ISSUE TITLE
Las peticiones por usuario deben de ser por username

### ISSUE THREAD

**Issue by ferferga** [ispp-2324-ocial/backend#127]
Hay varias peticiones que solicitan el id del usuario pero hay 3 ids en el modelo: el de django, el del ocialuser, y el del ocialclient. Por eso, en #116 se elimino el id del cuerpo y todas las búsquedas desde el cliente deben de hacerse por el username (que tenemos garantizado que es único). Exponer el id también es un problema de seguridad.

Hay otras peticiones donde tampoco queda claro si se solicita el ID de la entidad o el del cliente.

Listado completo de endpoints que habría que actualizar:

* POST /api/users/rating/{id}/
* PATCH /api/users/rating/{id}/
* DELETE /api/users/rating/{id}/
* GET /api/users/ratings/by-client/{id}/
* GET /api/event/client/{id}/

**Comment by adrrf** [comment]
de momento se va a fixear ell de events ya que los ratings no se van a implementar para este sprint
