### ISSUE TITLE
feat: medotodos de comprobación de suscripción

### ISSUE THREAD

**Issue by adrrf** [ispp-2324-ocial/backend#14]
Se necesita un método que dado un usuario me devuelva si puedo publicar un evento

**Comment by iniruimar** [comment]
Se debería añadir una variable que sea el número de eventos que han sido publicados en el mes?

**Comment by raumonmar1** [comment]
He estado planteando el problema y me voy a encargar de hacerlo durante esta semana. Haría falta incluir una fecha en la suscripción, de modo que a la hora de calcular los eventos que lleva el cliente, se tenga en cuenta siempre desde el día que compró la suscripción. 

Por ejemplo el cliente se suscribió el 3 de mayo y mantiene la suscripción hasta final de año pues cada día 3 de cada mes se le reinicien los eventos, o sea que no es tan simple

**Comment by iniruimar** [comment]
Hemos hecho que la suscripción tenga un fecha de comienzo y el fin de la suscripción sea 30 días después. Con esto hemos comprobado que los eventos publicados dentro de la fecha del periodo de suscripción sea menor que el número de eventos limite de la misma suscripción.
