### ISSUE TITLE
feat: modelado de datos Usuarios

### ISSUE THREAD

**Issue by lDrakohh** [ispp-2324-ocial/backend#2]

**Comment by fravilpae** [comment]
@ispp-2324-ocial/backend @ispp-2324-ocial/fullstack El usuario nativo de Django viene con unos atributos por defecto y no se puede editar para añadirle más atributos. Lo que se va a hacer es una nueva tabla con relación 1 a 1 al usuario nativo de django en el que ya se pondrán los atributos que faltan
