### ISSUE TITLE
feat: modelado de datos eventos

### ISSUE THREAD

**Issue by lDrakohh** [ispp-2324-ocial/backend#4]

**Comment by Jeszamgue** [comment]
@Domi-ATLAS el usuario ya ha sido creado en la rama feat/2-modelado-de-datos-usuario, faltaría el atributo de categoría favorita que habéis creado vosotros.

**Comment by adrrf** [comment]
METODO API EVENTOS DADO UN RADIO EN KM y UNA UBICACION

**Comment by adrrf** [comment]
IMPLEMENTAR OPEN API

**Comment by adrrf** [comment]
AÑADIR VALIDACION
