### ISSUE TITLE
FEATURE: social login

### ISSUE THREAD

**Issue by adrrf** [ispp-2324-ocial/backend#42]
Se debe permitir el registro e inicio de sesion de usuarios mediante
- google (SOLO SE HA IMPLEMENTADO ESTE)
- facebook
- instagram
- x

**Comment by lDrakohh** [comment]
Adjunto algunos enlaces de interés:
https://python-social-auth.readthedocs.io/en/latest/configuration/django.html
https://www.youtube.com/watch?v=8niPVU3oY0o
https://www.youtube.com/watch?v=yO6PP0vEOMc <- Este es el mas completo

**Comment by adrrf** [comment]
vamos a utilizar este tutorial para implementar en una primera instancia google, ya que es el más utilizado https://medium.com/codex/google-sign-in-rest-api-with-python-social-auth-and-django-rest-framework-4d087cd6d47f
