### ISSUE TITLE
FEATURE: Testing

### ISSUE THREAD

**Issue by adrrf** [ispp-2324-ocial/backend#43]
Se deben realizar test unitarios de todos los métodos y también hacer e2e para comprobar el correcto funcionamiento de la API

**Comment by lDrakohh** [comment]
Yo me encargo de avanzar en lo que pueda con los test de authentication

**Comment by lDrakohh** [comment]
Los test de Auth pasan correctamente las pruebas.
![Test auth](https://i.gyazo.com/c297963a22c4913a8f41e61574515596.png)

**Comment by raumonmar1** [comment]
He creado la rama feat/43-testing-event y he añadido test de eventos y valoraciones a falta del update-raiting que no consigo que me funcione.
![testing](https://github.com/ispp-2324-ocial/backend/assets/72814383/eefb9254-f377-4f66-a630-1737bfeabfae)
