### ISSUE TITLE
FEATURE: pasarela de pago pricing

### ISSUE THREAD

**Issue by adrrf** [ispp-2324-ocial/backend#45]
Se debe implementar la pasarela de pagos stripe para los pagos mensuales de las suscripciones

**Comment by raumonmar1** [comment]
@lDrakohh y yo hemos decidido separar las vistas de las suscripciones Basic y Pro. Actualmente funcionan ambas y tienen una primera versión en el frontend muy básica. @ispp-2324-ocial/frontend @ispp-2324-ocial/fullstack.

**Comment by lDrakohh** [comment]
Yo recomendaría una reunión para explicar cómo lo hemos hecho para los que vayan a integrar en el frontend.

Adjunto foto de las subscripciones funcionando.

!(test)[https://i.gyazo.com/6874536d45e519abda610513c480d89a.png]

**Comment by raumonmar1** [comment]
Ya tenemos la cancelación y reactivación de suscripción actualmente ambas funcionan de manera que cambias el parámetro de posición en la lista de suscripciones y borras ese elemento de la lista. La idea claramente no es esa sería primero comprobar la sesión iniciada comprobar si este usuario tiene o no suscripción activa y dependiendo de esto pues cambiar renovar o cancelar. @ispp-2324-ocial/backend
