### ISSUE TITLE
FEATURE: Migración de rating

### ISSUE THREAD

**Issue by adrrf** [ispp-2324-ocial/backend#46]
Los ratings tienen que ir asociados a los clientes y no a los eventos, los usuarios solo podrán poner un rating (valoracion de 1 a 5 y comentario) a un cliente. se debe pasar a una aplicacion de django externa (actualmente esta en rating y ahora esta en events)

**Comment by lDrakohh** [comment]
@adrrf La creo como una feature o como un hotfix?

**Comment by adrrf** [comment]
feat
