### ISSUE TITLE
FEATURE: Cambiar fecha y hora por datetime de Inicio y Fin de evento

### ISSUE THREAD

**Issue by carvarsou** [ispp-2324-ocial/backend#51]
Antes teníamos en el modelado de Eventos el inicio en hora y fecha de un Evento, ahora se debe tener una hora y fecha de Inicio y Fin de Evento, comprimido en un formato DateTime.

**Comment by Domi-ATLAS** [comment]
Hemos añadido la restricciones ademas de que un evento no pueda superar el dia de duración, ademas que nunca pueden situarse en fechas pasadas.
Dejo un link, con el codigo que sido de ayuda por si en vez de hacer una modificacion en el models.py, sea necesario hacer un filtrado en el view.py: https://stackoverflow.com/questions/40207560/django-queryset-filter-datetimefield-if-datetime-now-is-greater-than-field
