### ISSUE TITLE
FIX: Datos duplicados en la entidad `Event`

### ISSUE THREAD

**Issue by ferferga** [ispp-2324-ocial/backend#80]
Viendo la definición del swagger, el Base64 de la imagen se envía duplicado en ``imageB64`` y dentro de la entidad ``Image``:

![image](https://github.com/ispp-2324-ocial/backend/assets/10274099/0acd003c-0f2b-44e5-8301-f372274341f4)

Debería de mergearse en uno solo.

**Comment by adrrf** [comment]
creo distintas entidades de create y get
