### ISSUE TITLE
FIX: Testing

### ISSUE THREAD

**Issue by adrrf** [ispp-2324-ocial/backend#84]
Hay que arreglar los test de devlop (events dan errores, etc) y habria que quitar los de chat ya que no se va a implementar el sistema de chat

**Comment by lDrakohh** [comment]
Me encargo

**Comment by lDrakohh** [comment]
Todos los test corregidos y funcionando;

![Image](https://i.gyazo.com/9a5761f108838557cf18b01f74dceabb.png)

He añadido unos cuantos tests más para eventos, que habían solo 3, ahora hay 10.
